/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author LUCYLEONOR
 */
public class Video extends javax.swing.JFrame {

    /**
     * Creates new form Video
     */
    public Video() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdRestaurar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtND = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Tienda de Video");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Núm. de DVD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDKeyTyped(evt);
            }
        });
        jPanel1.add(txtD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 100, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Total a Pagar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        lblT.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 150, 30));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        cmdRestaurar.setText("Restaurar");
        cmdRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRestaurarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Núm. Dias");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        txtND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNDKeyTyped(evt);
            }
        });
        jPanel1.add(txtND, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed

        if (txtD.getText().trim().isEmpty() && txtD.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No Ha Ingresado Los Datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtD.requestFocusInWindow();
        } else if (txtD.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No Ha Ingresado El Numero De DVD", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtD.requestFocusInWindow();
        } else if (txtND.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No Ha Ingresado El Numero De DVD", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtND.requestFocusInWindow();
        } else if (txtD.getText().equalsIgnoreCase("0") || txtD.getText().equalsIgnoreCase("1")) {
            JOptionPane.showMessageDialog(this, "El numeros de peliculas debe ser superior a uno", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtD.requestFocusInWindow();
            txtD.selectAll();

        } else if (txtND.getText().equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(this, "El Numero De Dias Debe Der Superior A Uno", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtND.requestFocusInWindow();
            txtND.selectAll();
        } else {

            String R;
            double d, t, nd;

            d = Double.parseDouble(txtD.getText());
            nd = Double.parseDouble(txtND.getText());

            t = (d - 1) * (nd * 1500);

            R = String.valueOf(t);
            lblT.setText(R);

        }

    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRestaurarActionPerformed

        txtD.setText("");
        txtND.setText("");
        lblT.setText("");
        txtD.requestFocusInWindow();

    }//GEN-LAST:event_cmdRestaurarActionPerformed

    private void txtNDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNDKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtD.getText().trim().isEmpty() && txtND.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ha Ingresado Los Datos", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtD.requestFocusInWindow();

            } else if (txtD.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ha Ingresado El Numero De DVD", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtD.requestFocusInWindow();
            } else if (txtND.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ha Ingresado El Numero De DVD", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtND.requestFocusInWindow();
            } else if (txtD.getText().equalsIgnoreCase("0") || txtD.getText().equalsIgnoreCase("1")) {
                JOptionPane.showMessageDialog(this, "El numeros de peliculas debe ser superior a uno", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtD.requestFocusInWindow();
                txtD.selectAll();

            } else if (txtND.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(this, "El Numero De Dias Debe Der Superior A Uno", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtND.requestFocusInWindow();
                txtND.selectAll();
            } else {

                String R;
                double d, t, nd;

                d = Double.parseDouble(txtD.getText());
                nd = Double.parseDouble(txtND.getText());

                t = (d - 1) * (nd * 1500);

                R = String.valueOf(t);
                lblT.setText("$ " + R);

            }

        }
    }//GEN-LAST:event_txtNDKeyPressed

    private void txtDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_txtDKeyTyped

    private void txtDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (txtD.getText().trim().isEmpty() && txtD.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ha Ingresado Los Datos", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtD.requestFocusInWindow();
            } else if (txtD.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ha Ingresado El Numero De DVD", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtD.requestFocusInWindow();
            } else if (txtND.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ha Ingresado El Numero De Dias", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtND.requestFocusInWindow();
            } else if (txtD.getText().equalsIgnoreCase("0") || txtD.getText().equalsIgnoreCase("1")) {
                JOptionPane.showMessageDialog(this, "El numeros de peliculas debe ser superior a uno", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtD.requestFocusInWindow();
                txtD.selectAll();
            } else if (txtND.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(this, "El Numero De Dias Debe Der Superior A Uno", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtND.requestFocusInWindow();
                txtND.selectAll();

            } else {

                String R;
                double d, t, nd;

                d = Double.parseDouble(txtD.getText());
                nd = Double.parseDouble(txtND.getText());

                t = (d - 1) * (nd * 1500);

                R = String.valueOf(t);
                lblT.setText("$ " + R);

            }

        }
    }//GEN-LAST:event_txtDKeyPressed

    private void txtNDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNDKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Video().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdRestaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblT;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtND;
    // End of variables declaration//GEN-END:variables
}
